# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020 Innovative Electronics, LLC
#		     Dennis Lambe Jr. <dlambe@innovative-electronics.com>

obj-y += onsite_te5000.o
obj-$(CONFIG_I2C_EEPROM) += ../../atmel/common/mac_eeprom.o
obj-$(CONFIG_CMD_CLCD) += clcd.o
obj-$(CONFIG_CMD_FATAL) += fatal_message.o
